# Generated by Django 4.1 on 2024-01-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditory_skills", "0002_alter_gamedata_dateplayed"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervalquizdata",
            name="questionTimes",
            field=models.JSONField(default=list),
        ),
    ]
